-- BAF-11 stage 4: installs/installs_retarget (installs_report + installs-retarget v5
-- endpoints), full 128-column pass-through. Column set/types per the live measurement in
-- docs/superpowers/specs/2026-08-13-baf-11-column-sizing.md (2026-08-13, com.yesimmobile,
-- 2026-08-11: 1,872 installs_report rows, 918 installs-retarget rows). Empty-in-sample
-- columns are typed by semantic category, not guessed per-column -- see
-- docs/superpowers/plans/2026-08-31-baf-11-stage-4-installs-report.md's Architecture
-- decision 6 for the categorization rule and the byte-budget arithmetic (~28.4 KB of the
-- 65,535-byte row limit).
--
-- `install_time`/`event_time`/`appsflyer_id` are NOT NULL: ReportSpec.required_not_null
-- guarantees this before a row ever reaches the INSERT (a row missing any of them is
-- skipped-and-counted, not persisted with a blank).
--
-- installs' own dedupe key is (appsflyer_id, event_time) -- NOT in-app-events' key. See
-- the plan above (Architecture decision 7) for the full rationale and the open risk
-- flagged for Mark/data-analytics sign-off.
--
-- This file documents the schema for reference and manual execution; `appsflyer-pipeline
-- create-table` creates it programmatically (idempotent) using the table name configured
-- via DB_TABLE_INSTALLS -- keep the two in sync.

CREATE TABLE IF NOT EXISTS `appsflyer_installs_fb` (
    `id`                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attributed_touch_type`           VARCHAR(32)    NULL,
    `attributed_touch_time`           DATETIME       NULL,
    `install_time`                    DATETIME       NOT NULL,
    `event_time`                      DATETIME       NOT NULL,
    `event_name`                      VARCHAR(32)    NULL,
    `event_value`                     TEXT           NULL,
    `event_revenue`                   DECIMAL(18,4)  NULL,
    `event_revenue_currency`          VARCHAR(16)    NULL,
    `event_revenue_usd`               DECIMAL(18,4)  NULL,
    `event_source`                    VARCHAR(16)    NULL,
    `is_receipt_validated`            VARCHAR(16)    NULL,
    `partner`                         VARCHAR(64)    NULL,
    `media_source`                    VARCHAR(64)    NULL,
    `channel`                         VARCHAR(32)    NULL,
    `keywords`                        VARCHAR(128)   NULL,
    `campaign`                        VARCHAR(128)   NULL,
    `campaign_id`                     VARCHAR(64)    NULL,
    `adset`                           VARCHAR(128)   NULL,
    `adset_id`                        VARCHAR(64)    NULL,
    `ad`                              VARCHAR(128)   NULL,
    `ad_id`                           VARCHAR(64)    NULL,
    `ad_type`                         VARCHAR(64)    NULL,
    `site_id`                         VARCHAR(128)   NULL,
    `sub_site_id`                     VARCHAR(64)    NULL,
    `sub_param_1`                     VARCHAR(16)    NULL,
    `sub_param_2`                     VARCHAR(64)    NULL,
    `sub_param_3`                     VARCHAR(64)    NULL,
    `sub_param_4`                     VARCHAR(255)   NULL,
    `sub_param_5`                     VARCHAR(128)   NULL,
    `cost_model`                      VARCHAR(32)    NULL,
    `cost_value`                      DECIMAL(18,4)  NULL,
    `cost_currency`                   VARCHAR(16)    NULL,
    `contributor_1_partner`           VARCHAR(64)    NULL,
    `contributor_1_media_source`      VARCHAR(64)    NULL,
    `contributor_1_campaign`          VARCHAR(128)   NULL,
    `contributor_1_touch_type`        VARCHAR(32)    NULL,
    `contributor_1_touch_time`        VARCHAR(64)    NULL,
    `contributor_2_partner`           VARCHAR(64)    NULL,
    `contributor_2_media_source`      VARCHAR(64)    NULL,
    `contributor_2_campaign`          VARCHAR(128)   NULL,
    `contributor_2_touch_type`        VARCHAR(32)    NULL,
    `contributor_2_touch_time`        VARCHAR(64)    NULL,
    `contributor_3_partner`           VARCHAR(64)    NULL,
    `contributor_3_media_source`      VARCHAR(64)    NULL,
    `contributor_3_campaign`          VARCHAR(128)   NULL,
    `contributor_3_touch_type`        VARCHAR(32)    NULL,
    `contributor_3_touch_time`        VARCHAR(64)    NULL,
    `region`                          VARCHAR(16)    NULL,
    `country_code`                    VARCHAR(16)    NULL,
    `state`                           VARCHAR(32)    NULL,
    `city`                            VARCHAR(64)    NULL,
    `postal_code`                     VARCHAR(32)    NULL,
    `dma`                             VARCHAR(16)    NULL,
    `ip`                              VARCHAR(32)    NULL,
    `wifi`                            VARCHAR(16)    NULL,
    `operator`                        VARCHAR(128)   NULL,
    `carrier`                         VARCHAR(128)   NULL,
    `language`                        VARCHAR(32)    NULL,
    `appsflyer_id`                    VARCHAR(128)   NOT NULL,
    `advertising_id`                  VARCHAR(128)   NULL,
    `idfa`                            VARCHAR(128)   NULL,
    `android_id`                      VARCHAR(128)   NULL,
    `customer_user_id`                VARCHAR(255)   NULL,
    `imei`                            VARCHAR(64)    NULL,
    `idfv`                            VARCHAR(128)   NULL,
    `platform`                        VARCHAR(16)    NULL,
    `device_type`                     VARCHAR(32)    NULL,
    `os_version`                      VARCHAR(16)    NULL,
    `app_version`                     VARCHAR(32)    NULL,
    `sdk_version`                     VARCHAR(16)    NULL,
    `appsflyer_app_id`                VARCHAR(32)    NULL,
    `app_name`                        VARCHAR(128)   NULL,
    `bundle_id`                       VARCHAR(64)    NULL,
    `is_retargeting`                  VARCHAR(16)    NULL,
    `retargeting_conversion_type`     VARCHAR(32)    NULL,
    `attribution_lookback`            VARCHAR(16)    NULL,
    `reengagement_window`             VARCHAR(16)    NULL,
    `is_primary_attribution`          VARCHAR(16)    NULL,
    `user_agent`                      TEXT           NULL,
    `http_referrer`                   TEXT           NULL,
    `original_url`                    TEXT           NULL,
    `store_reinstall`                 VARCHAR(16)    NULL,
    `impressions`                     VARCHAR(32)    NULL,
    `contributor_3_match_type`        VARCHAR(32)    NULL,
    `custom_dimension`                VARCHAR(64)    NULL,
    `conversion_type`                 VARCHAR(32)    NULL,
    `google_play_click_time`          VARCHAR(64)    NULL,
    `match_type`                      VARCHAR(32)    NULL,
    `mediation_network`               VARCHAR(64)    NULL,
    `oaid`                            VARCHAR(64)    NULL,
    `deeplink_url`                    TEXT           NULL,
    `blocked_reason`                  VARCHAR(64)    NULL,
    `blocked_sub_reason`              VARCHAR(64)    NULL,
    `google_play_broadcast_referrer`  TEXT           NULL,
    `google_play_install_begin_time`  VARCHAR(64)    NULL,
    `campaign_type`                   VARCHAR(32)    NULL,
    `custom_data`                     TEXT           NULL,
    `rejected_reason`                 VARCHAR(64)    NULL,
    `device_download_time`            VARCHAR(64)    NULL,
    `keyword_match_type`              VARCHAR(16)    NULL,
    `contributor_1_match_type`        VARCHAR(32)    NULL,
    `contributor_2_match_type`        VARCHAR(32)    NULL,
    `device_model`                    VARCHAR(128)   NULL,
    `monetization_network`            VARCHAR(64)    NULL,
    `segment`                         VARCHAR(64)    NULL,
    `is_lat`                          VARCHAR(16)    NULL,
    `google_play_referrer`            TEXT           NULL,
    `blocked_reason_value`            VARCHAR(32)    NULL,
    `store_product_page`              VARCHAR(32)    NULL,
    `device_category`                 VARCHAR(64)    NULL,
    `app_type`                        VARCHAR(32)    NULL,
    `rejected_reason_value`           VARCHAR(32)    NULL,
    `ad_unit`                         VARCHAR(64)    NULL,
    `keyword_id`                      VARCHAR(64)    NULL,
    `placement`                       VARCHAR(64)    NULL,
    `network_account_id`              VARCHAR(64)    NULL,
    `install_app_store`               VARCHAR(32)    NULL,
    `amazon_fire_id`                  VARCHAR(128)   NULL,
    `att`                             VARCHAR(16)    NULL,
    `engagement_type`                 VARCHAR(64)    NULL,
    `contributor_1_engagement_type`   VARCHAR(64)    NULL,
    `contributor_2_engagement_type`   VARCHAR(64)    NULL,
    `contributor_3_engagement_type`   VARCHAR(64)    NULL,
    `gdpr_applies`                    VARCHAR(16)    NULL,
    `ad_user_data_enabled`            VARCHAR(16)    NULL,
    `ad_personalization_enabled`      VARCHAR(16)    NULL,
    `total_candidates`                VARCHAR(16)    NULL,
    `engagement_destination`          VARCHAR(32)    NULL,
    `attribution_type`                VARCHAR(50)    NOT NULL,
    `app_id`                          VARCHAR(100)   NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_app_attr_install` (`app_id`, `attribution_type`, `install_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
